USE [master]
GO

/****** Object:  Database [CleanPlanet]    Script Date: 23.10.2025 12:15:41 ******/
CREATE DATABASE [CleanPlanet]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CleanPlanet', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CleanPlanet.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CleanPlanet_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CleanPlanet_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CleanPlanet].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CleanPlanet] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CleanPlanet] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CleanPlanet] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CleanPlanet] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CleanPlanet] SET ARITHABORT OFF 
GO

ALTER DATABASE [CleanPlanet] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CleanPlanet] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CleanPlanet] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CleanPlanet] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CleanPlanet] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CleanPlanet] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CleanPlanet] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CleanPlanet] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CleanPlanet] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CleanPlanet] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CleanPlanet] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CleanPlanet] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CleanPlanet] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CleanPlanet] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CleanPlanet] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CleanPlanet] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CleanPlanet] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CleanPlanet] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CleanPlanet] SET  MULTI_USER 
GO

ALTER DATABASE [CleanPlanet] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CleanPlanet] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CleanPlanet] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CleanPlanet] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CleanPlanet] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CleanPlanet] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CleanPlanet] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CleanPlanet] SET  READ_WRITE 
GO

